-- MySQL Script generated by MySQL Workbench
-- Sun Sep 24 14:50:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema seguros
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema seguros
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `seguros` DEFAULT CHARACTER SET utf8mb3 ;
USE `seguros` ;

-- -----------------------------------------------------
-- Table `seguros`.`calle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguros`.`calle` (
  `idNumeroCalle` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(10) NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idNumeroCalle`),
  UNIQUE INDEX `numero_UNIQUE` (`numero` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `seguros`.`Provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguros`.`Provincia` (
  `idProvincia` INT NOT NULL AUTO_INCREMENT,
  `nombreProvincia` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idProvincia`),
  UNIQUE INDEX `nombreCiudad_UNIQUE` (`nombreProvincia` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `seguros`.`ciudades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguros`.`ciudades` (
  `idCiudad` INT NOT NULL AUTO_INCREMENT,
  `nombreCiudad` VARCHAR(255) NOT NULL,
  `Provincia_idProvincia` INT NOT NULL,
  PRIMARY KEY (`idCiudad`),
  UNIQUE INDEX `nombreCiudad_UNIQUE` (`nombreCiudad` ASC) VISIBLE,
  INDEX `fk_ciudades_Provincia1_idx` (`Provincia_idProvincia` ASC) VISIBLE,
  CONSTRAINT `fk_ciudades_Provincia1`
    FOREIGN KEY (`Provincia_idProvincia`)
    REFERENCES `seguros`.`Provincia` (`idProvincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `seguros`.`direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguros`.`direccion` (
  `idDireccion` INT NOT NULL AUTO_INCREMENT,
  `calle_idNumeroCalle` INT NOT NULL,
  `ciudades_idCiudad` INT NOT NULL,
  PRIMARY KEY (`idDireccion`),
  INDEX `fk_direcciones_calle1_idx` (`calle_idNumeroCalle` ASC) VISIBLE,
  INDEX `fk_direccion_ciudades1_idx` (`ciudades_idCiudad` ASC) VISIBLE,
  CONSTRAINT `fk_direcciones_calle1`
    FOREIGN KEY (`calle_idNumeroCalle`)
    REFERENCES `seguros`.`calle` (`idNumeroCalle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_direccion_ciudades1`
    FOREIGN KEY (`ciudades_idCiudad`)
    REFERENCES `seguros`.`ciudades` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `seguros`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguros`.`persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `apellido` VARCHAR(32) NOT NULL,
  `telefono` VARCHAR(32) NOT NULL,
  `direcciones_idDireccion` INT NOT NULL,
  PRIMARY KEY (`idPersona`),
  INDEX `fk_persona_direcciones1_idx` (`direcciones_idDireccion` ASC) VISIBLE,
  CONSTRAINT `fk_persona_direcciones1`
    FOREIGN KEY (`direcciones_idDireccion`)
    REFERENCES `seguros`.`direccion` (`idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `seguros`.`agente_de_seguros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguros`.`agente_de_seguros` (
  `idAsegurador` INT NOT NULL AUTO_INCREMENT,
  `persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idAsegurador`),
  INDEX `fk_agente_de_seguros_persona1_idx` (`persona_idPersona` ASC) VISIBLE,
  CONSTRAINT `fk_agente_de_seguros_persona1`
    FOREIGN KEY (`persona_idPersona`)
    REFERENCES `seguros`.`persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `seguros`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguros`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `puntosCompania` VARCHAR(45) NULL,
  `persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_cliente_persona1_idx` (`persona_idPersona` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_persona1`
    FOREIGN KEY (`persona_idPersona`)
    REFERENCES `seguros`.`persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `seguros`.`cobertura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguros`.`cobertura` (
  `idCobertura` INT NOT NULL AUTO_INCREMENT,
  `tipo_cobertura` VARCHAR(255) NOT NULL,
  `descripcion` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`idCobertura`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `seguros`.`poliza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguros`.`poliza` (
  `idPoliza` INT NOT NULL AUTO_INCREMENT,
  `numero_de_poliza` INT NOT NULL,
  `fecha_de_emision` DATE NOT NULL,
  `fecha_de_vencimiento` DATE NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Agente_de_Seguros_idAsegurador` INT NOT NULL,
  `cobertura_idCobertura` INT NOT NULL,
  PRIMARY KEY (`idPoliza`),
  INDEX `fk_Poliza_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Poliza_Agente_de_Seguros1_idx` (`Agente_de_Seguros_idAsegurador` ASC) VISIBLE,
  INDEX `fk_poliza_cobertura1_idx` (`cobertura_idCobertura` ASC) VISIBLE,
  CONSTRAINT `fk_Poliza_Agente_de_Seguros1`
    FOREIGN KEY (`Agente_de_Seguros_idAsegurador`)
    REFERENCES `seguros`.`agente_de_seguros` (`idAsegurador`),
  CONSTRAINT `fk_Poliza_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `seguros`.`cliente` (`idCliente`),
  CONSTRAINT `fk_poliza_cobertura1`
    FOREIGN KEY (`cobertura_idCobertura`)
    REFERENCES `seguros`.`cobertura` (`idCobertura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `seguros`.`modificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguros`.`modificacion` (
  `idModificacion` INT NOT NULL AUTO_INCREMENT,
  `fecha_modificacion` DATE NOT NULL,
  `descripcion` VARCHAR(32) NOT NULL,
  `Agente_de_Seguros_idAsegurador` INT NOT NULL,
  `Poliza_idPoliza` INT NOT NULL,
  PRIMARY KEY (`idModificacion`),
  INDEX `fk_Modificacion_Agente_de_Seguros1_idx` (`Agente_de_Seguros_idAsegurador` ASC) VISIBLE,
  INDEX `fk_Modificacion_Poliza1_idx` (`Poliza_idPoliza` ASC) VISIBLE,
  CONSTRAINT `fk_Modificacion_Agente_de_Seguros1`
    FOREIGN KEY (`Agente_de_Seguros_idAsegurador`)
    REFERENCES `seguros`.`agente_de_seguros` (`idAsegurador`),
  CONSTRAINT `fk_Modificacion_Poliza1`
    FOREIGN KEY (`Poliza_idPoliza`)
    REFERENCES `seguros`.`poliza` (`idPoliza`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `seguros`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguros`.`pago` (
  `idPago` INT NOT NULL AUTO_INCREMENT,
  `fecha_pago` DATE NOT NULL,
  `monto` FLOAT NOT NULL,
  `mesAPagar` VARCHAR(45) NOT NULL,
  `metodo de pago` VARCHAR(45) NOT NULL,
  `comision` INT NOT NULL,
  `Poliza_idPoliza` INT NOT NULL,
  `Agente_de_Seguros_idAsegurador` INT NOT NULL,
  PRIMARY KEY (`idPago`),
  INDEX `fk_Pago_Poliza1_idx` (`Poliza_idPoliza` ASC) VISIBLE,
  INDEX `fk_Pago_Agente_de_Seguros1_idx` (`Agente_de_Seguros_idAsegurador` ASC) VISIBLE,
  CONSTRAINT `fk_Pago_Agente_de_Seguros1`
    FOREIGN KEY (`Agente_de_Seguros_idAsegurador`)
    REFERENCES `seguros`.`agente_de_seguros` (`idAsegurador`),
  CONSTRAINT `fk_Pago_Poliza1`
    FOREIGN KEY (`Poliza_idPoliza`)
    REFERENCES `seguros`.`poliza` (`idPoliza`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `seguros`.`reclamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguros`.`reclamo` (
  `idReclamo` INT NOT NULL AUTO_INCREMENT,
  `fecha_reclamo` DATE NOT NULL,
  `descripcion` VARCHAR(32) NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Agente_de_Seguros_idAsegurador` INT NOT NULL,
  PRIMARY KEY (`idReclamo`),
  INDEX `fk_Reclamo_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Reclamo_Agente_de_Seguros1_idx` (`Agente_de_Seguros_idAsegurador` ASC) VISIBLE,
  CONSTRAINT `fk_Reclamo_Agente_de_Seguros1`
    FOREIGN KEY (`Agente_de_Seguros_idAsegurador`)
    REFERENCES `seguros`.`agente_de_seguros` (`idAsegurador`),
  CONSTRAINT `fk_Reclamo_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `seguros`.`cliente` (`idCliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
